import './globals.css';
import {Poppins} from 'next/font/google';

const fontPoppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '700', '800', '900'],
	style: ['normal', 'italic'],
	display: 'swap',
	variable: '--font-poppins',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({children}: {children: React.ReactNode}) => (
	<html
		lang='en'
		className={`h-full min-w-[360px] scroll-smooth bg-white ${fontPoppins.variable}`}
	>
		<body className='min-h-screen antialiased'>
			<main className='flex h-full min-h-screen w-full flex-1 flex-col items-center justify-center bg-white text-center text-black'>
				{children}
			</main>
		</body>
	</html>
);

export default RootLayout;
